version: '3'

services:
  api:
    build: 
        context: .
        dockerfile: ./backend/Dockerfile
    command: uvicorn backend.buffer.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./:/app
    ports:
      - 8001:8001
    env_file:
      - ./backend/buffer/.env
    environment: 
      - REDIS_HOST=redis
    depends_on:
      - redis      
  
  redis:
    image: redis:6.2-alpine
    ports:
        - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes